repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks-system
        pass_filenames: false
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: \.sh(\.tmpl)?$
      - id: fish-syntax
        name: fish -n
        entry: fish --no-execute
        language: system
        files: \.fish$
